export const noResults: string[] = [
  "Nothing came up for your query.",
  "Unfortunately, I couldn't find anything.",
  "I didn't find anything.",
];
export const heartsEmojies: string[] = ["💜", "💖", "💝", "💗", "💓"];
export const recomendations: string[] = [
  "Светлана Резанова",
  "VSN7, ▽",
  "Chiiild",
  "Itoko Toma",
  "If you have no friends",
  "The 1975",
  "Hello Saferide",
  "Clairo",
  "Claire laffut",
  "Araki shin",
  "polnalyubvi",
  "Louis the Child",
  "Frank Ocean",
  "Daft Punk",
  "Crystal Castles",
  "Melanie Martinez",
  "Mura Masa",
  "Ironomi",
  "Winona Oak",
  "LO FI LE VI",
  "Holly Humberstone",
  "Park Hye Jin",
  "Jordan Rakei",
  "The Drums",
  "The XX",
  "Harrison Brome",
  "Sales",
  "Slowdive",
  "Joey bada",
  "Joey pecoraro",
  "Dead Poet Society",
  "Good Morning Jazz Academy",
  "Twenty One Pilots",
  "Nick Cave",
  "Dead man's bones",
  "Zanski",
  "Юлия Кошкина",
  "Hollow Coves",
  "Connan Mockasin",
  "Olivia Rodrigo",
  "The lumineers",
  "Bibio",
  "Car Seat Headrest",
  "White katana",
  "Princess Chelsea",
  "Jack Stauber",
  "Alvvays",
  "Dominic Fike",
  "RHYE",
  "Стереополина",
  "Years & Years",
  "London Grammar",
  "Foals",
  "Colouring",
  "Cleopatrick",
  "The Saxophones",
];
