export const noResults: string[] = ["Nothing came up for your query.", "Unfortunately, I couldn't find anything.", "I didn't find anything."];
export const heartsEmojies: string[] = ["💜", "💖", "💝", "💗", "💓"];
export const recomendations: string[] = [
  "Chiiild",
  "Itoko Toma",
  "If you have no friends",
  "The 1975",
  "Hello Saferide",
  "Clairo",
  "Claire laffut",
  "Araki shin",
  "polnalyubvi",
  "Louis the Child",
  "Frank Ocean",
  "Daft Punk",
  "Crystal Castles",
  "Melanie Martinez",
  "Mura Masa",
  "Ironomi",
  "Winona Oak",
  "LO FI LE VI",
  "Holly Humberstone",
  "Park Hye Jin",
  "Jordan Rakei",
  "The Drums",
  "The XX",
  "Harrison Brome",
  "Sales",
  "Slowdive",
  "Joey bada",
  "Joey pecoraro",
  "Dead Poet Society",
  "good morning jazz academy",
  "Twenty One Pilots",
  "Nick Cave",
  "Dead man's bones",
];
